# Generated by Django 4.2.5 on 2023-10-13 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogin',
            old_name='pasword',
            new_name='password',
        ),
    ]
