# Generated by Django 4.2.5 on 2023-10-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_pasword_userlogin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
